matkulList/urls.py
from django.urls import  path

from . import views

app_name = 'matkulList'

urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add, name="add"),
    path('view/<int:id>', views.view, name="view"),
    path('delete/<int:id>', views.remove, name="delete")
]

ppwstory1/urls.py
from django.urls import include, path

from . import views

app_name = "ppwstory1"

urlpatterns = [
    path('', views.index, name="index"),
    path('profile/', views.viewProfile, name="profile")
]

ppwstory3/urls.py
from django.urls import include, path

from . import views

app_name = "ppwstory3"

urlpatterns = [
    path('', views.index, name="index"),
    path('profile/', views.profile, name="profile"),
    path('posts/', views.posts, name="posts"),
    path('posts/<int:number>', views.posts, name="posts")
]

ppwstory5/urls.py
from django.contrib import admin
from django.urls import  include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ppwstory1/', include('ppwstory1.urls')),
    path('matkul/', include('matkulList.urls')),
    path('', include('ppwstory3.urls'))
]

matkulList/models.py
import re
from django.utils.translation import gettext_lazy as _

from django import forms
from django.db import models

termpattern = re.compile(r"^\b(Gasal|Genap) \d{4}\/\d{4}$")
locpattern1 = re.compile(r"^\d{1}\.\d{4}$")
locpattern2 = re.compile(r"^([A-Z])\d{1}\.\d{2}$")

class MatKul(models.Model):
    title = models.CharField(max_length=100)
    term = models.CharField(max_length=15)
    lecturer = models.CharField(max_length=100)
    total_credits = models.IntegerField()
    location = models.CharField(max_length=50)
    description = models.TextField(max_length=2000)

    def __str__(self):
        return self.title



class MatKulForm(forms.ModelForm):
    class Meta:
        model = MatKul
        fields = ['title', 'term', 'lecturer', 'total_credits', 'location', 'description']
        labels = {
            'total_credits' : _('Total credits')
        }

    def clean(self):
        super(MatKulForm, self).clean()

        term = self.cleaned_data.get('term')

        if (not termpattern.match(term)):
            self._errors['term'] = self.error_class(
                ['Incorrect term format! (Should be "Gasal 2019/2020" or "Genap 2019/2020" in any year)']
            )

        return self.cleaned_data
        

ppwstory1/models.py
from django.db import models

# Create your models here.

ppwstory3/models.py
from django.db import models

# Create your models here.

matkulList/views.py
from .models import MatKul, MatKulForm
from django.contrib.messages import get_messages, success, error
from django.http import HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect, render, reverse

def index(request):
    messages = get_messages(request)
    matkulList = MatKul.objects.all()
    return render(request, 'matkulList/index.html', {'matkulList' : matkulList, "messages" : messages})

def view(request, id):
    matkul = MatKul.objects.filter(pk=id).first()
    if (matkul == None):
        error(request, "Matkul tidak ditemukan!")
        return redirect(reverse("matkulList:index"))
    return render(request, 'matkulList/view.html', {'matkul' : matkul})

def add(request):
    if (request.method == "POST"):
        form = MatKulForm(request.POST)
        if (form.is_valid()):
            matkul = MatKulForm.save(form)
            success(request, "Matkul telah ditambahkan!")
            return redirect(reverse('matkulList:index'))
        else:
            return render(request, 'matkulList/add.html', {'form' : form})
    else:
        form = MatKulForm()
    
    return render(request, 'matkulList/add.html', {'form' : form})

def remove(request, id):
    matkul = MatKul.objects.filter(pk=id).first()
    if (matkul == None):
        error(request, "Matkul tidak ditemukan!")
        return redirect(reverse("matkulList:index"))
    if (request.method == "POST"):
        MatKul.delete(matkul)
        success(request, "Matkul telah dihapus!")
        return redirect(reverse("matkulList:index"))
    else:
        return render(request, 'matkulList/remove.html', {'matkul' : matkul})

ppwstory1/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'ppwstory1/index.html')

def viewProfile(request):
    return render(request, 'ppwstory1/profile.html')

ppwstory3/views.py
from django.http import Http404
from django.shortcuts import redirect, render, reverse
from django.template import TemplateDoesNotExist

from .apps import postdict, desdict

def index(request):
    return render(request, 'ppwstory3/index.html', {'postdict':postdict, "desdict": desdict, "range":range(1,len(postdict)+1)})

def profile(request):
    return render(request, 'ppwstory3/profile.html')

def posts(request, number=0):
    if (number==0):
        return redirect(reverse('ppwstory3:index'))
    else:
        return render(request, 'ppwstory3/posts/' + str(number) + ".html")

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        {% block head %} {% endblock %}
    </head>
    <body>
        {% block body %} {% endblock %}
    </body>
</html>

templates/matkulList/add.html
{% extends "matkulList/base.html" %}
{% load ppwstory3Customtags %}

{% block addition %}- Add Matkul{% endblock %}

{% load static %}
{% load bootstrap4 %}
{% block matkulstuff %}
<h2>Add Matkul</h2>
<form action="{% url 'matkulList:add' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn" type="submit" value="add">
</form>
{% endblock %}

templates/matkulList/base.html
{% extends "ppwstory3/base.html" %}

{% block title %}MatkulList {% block addition %}{% endblock %}{% endblock %}

{% block content %}
<h1>Matkul List</h1>
{% block matkulstuff %}
{% endblock %}
{% endblock %}
{% block sidebar %}
<p>Learning web development. Enthutiastic in learning new stuffs.</p>
{% endblock %}

templates/matkulList/index.html
{% extends "matkulList/base.html" %}
{% load ppwstory3Customtags %}

{% block addition %}{% endblock %}

{% load static %}
{% block matkulstuff %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}class="alert alert-danger"
    {% else %} class="alert alert-success" {% endif %}>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
<a class="btn" style="margin: 10px;" href="{% url 'matkulList:add' %}">add</a>
<ul>
    {% for matkul in matkulList %}
    <li>
        <div class="postpreview">
            <div class="textbox">
                <h2><a href="{% url 'matkulList:view' matkul.pk %}">{{ matkul.title }}</a></h2>
                <p>
                    {{ matkul.term }}<br>
                    Lecturer: {{ matkul.lecturer }}<br>
                    Total credits: {{ matkul.total_credits }} credits<br>
                    Location: {{ matkul.location }}
                </p>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/matkulList/remove.html
{% extends "matkulList/base.html" %}
{% load ppwstory3Customtags %}

{% block addition %}{% endblock %}

{% load static %}
{% block matkulstuff %}
<h2>Delete Matkul</h2>
<p>Are you sure you want to delete <b>{{ matkul.title }}</b>?</p>
<form action="" method="POST">
    {% csrf_token %}
    <div style="display: block-inline;">
        <input class="btn" type="submit" value="Delete">
        <a class="btn" href="{% url 'matkulList:view' matkul.pk %}">Go back</a>
    </div>
</form>
{% endblock %}

templates/matkulList/view.html
{% extends "matkulList/base.html" %}
{% load ppwstory3Customtags %}

{% block addition %}- {{ matkul.title }}{% endblock %}

{% load static %}
{% block matkulstuff %}
<h2>{{ matkul.title }}</h2>
<p><b>{{ matkul.term }}</b></p>
<p><b>Lecturer:</b> {{ matkul.lecturer }}</p>
<p><b>Total credits:</b> {{ matkul.total_credits }} credits</p>
<p><b>Location:</b> {{ matkul.location }}</p>
<P><b>Description:</b><br>{{matkul.description }}</P>
<div style="display: inline-block;">
    <a class="btn" href="{% url 'matkulList:delete' matkul.pk %}">Delete</a>
    <a class="btn" href="{% url 'matkulList:index' %}">Back</a>
</div>
{% endblock %}

templates/ppwstory1/base.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>PPW Story 1 | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'ppwstory1/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
{% endblock %}
{% block body %}
        <div class="navbar">
            <ul>
                <li><a href="{% url 'ppwstory1:index' %}">PPW Story 1</a></li>
                <li><a href="{% url 'ppwstory3:index' %}">PPW Story 5</a></li>
            </ul>
        </div>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        <div class="footer">
            <p>Created in 2020 by William</p>
        </div>
{% endblock %}

templates/ppwstory1/index.html
{% extends 'ppwstory1/base.html' %}
{% load static %}
{% block title %} Selamat Datang! {% endblock %}
{% block content %}
    <h2>Selamat Datang!</h2>
    <p>Selamat datang di web pertama saya!</p>
    <img alt="ProfilePic" src="{% static 'ppwstory1/profilepic.jpg' %}">
    <h2>William</h2>
    <p>Gemar mempelajari hal-hal baru</p>
    <div class="button">
        <a href="{% url 'ppwstory1:profile' %}">Tampilkan</a>
    </div>
{% endblock %}

templates/ppwstory1/profile.html
{% extends 'ppwstory1/base.html' %}
{% load static %}
{% block title %}Profile Saya{% endblock %}
{% block content %}
    <h2>Profile Saya</h2>
    <img alt="ProfilePic" src="{% static 'ppwstory1/profilepic.jpg' %}">
    <table>
        <tr>
            <td>Nama</td>
            <td>William</td>
        </tr> 
        <tr>
            <td>NPM</td>
            <td>1906350521</td>
        </tr>
        <tr>
            <td>Angkatan</td>
            <td>2019</td>
        </tr>
    </table>
    <h2>Hobi</h2>
    <p>Main game, Belajar hal baru</p>
    <h2>Deskripsi</h2>
    <p>
        Aku suka belajar hal-hal baru, namun aku cepat bosan. Sebelum kuliah, aku sudah belajar pemrograman,
        tapi sepertinya aku perlu belajar lebih banyak lagi.
    </p>
    <h2>Riwayat pendidikan</h2>
    <ul>
        <li>
            <p>S1 Ilmu Komputer, Universitas Indonesia (2019 - sekarang)</p>
        </li>
        <li>
            <p>SMA Negeri 2 Jakarta (2016 - 2019)</p>
        </li>
        <li>
            <p>SMP Kristen 2 BPK Penabur (2016 - 2013)</p>
        </li>
    </ul>
    <h2>
        Kontak
    </h2>
    <div class="contact">
        <a href="https://twitter.com/hori_75">
            <img alt="twitter" src="{% static 'ppwstory1/twitter.png' %}">
        </a>
        <a href="https://www.linkedin.com/in/william-8611851a0/">
            <img alt="linkedin" src="{% static 'ppwstory1/linkedin.png' %}" style="max-width: 59px; max-height: 59px;">
        </a>
    </div>
{% endblock %}

templates/ppwstory3/base.html
{% extends 'base.html' %}

{% load static %}
{% block head %}
    <title>PPW Story 5 | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'ppwstory3/css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 sidebar">
                <img alt="William's photo" src="{% static 'ppwstory3/img/William.png' %}">
                <h2>William</h2>
                {% block sidebar %}
                {% endblock %}
                <div class="sidebar-button">
                    <ul>
                        <li><a class="btn" href="{% url 'ppwstory3:index' %}">Main Page</a></li>
                        <li><a class="btn" href="{% url 'ppwstory3:profile' %}">View Profile</a></li>
                        <li><a class="btn" href="{% url 'ppwstory1:index' %}">PPW Story 1</a></li>
                        <li><a class="btn" href="{% url 'matkulList:index' %}">Matkul List</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-9 col-md-offset-3 content">
                <div class="content">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/ppwstory3/index.html
{% extends "ppwstory3/base.html" %}
{% load ppwstory3Customtags %}

{% block title %}Summary{% endblock %}

{% load static %}
{% block content %}
<h1>See What I have worked on...</h1>
<ul>
    {% for i in range %}
    <li>
        <div class="postpreview">
            <img alt="{{i}}" src="{% static 'ppwstory3/img/'|get_thumbnail:i %}">
            <div class="textbox">
                <h2><a href="{% url 'ppwstory3:posts' i %}">{{ postdict|get_item:i }}</a></h2>
                <p>{{ desdict|get_item:i }}</p>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}
{% block sidebar %}
<p>Learning web development. Enthutiastic in learning new stuffs.</p>
{% endblock %}
{% block buttons %}
<li><a class="btn" href="{% url 'ppwstory3:profile' %}">View Profile</a></li>
<li><a class="btn" href="{% url 'matkulList:index' %}">Matkul List</a></li>
{% endblock %}

templates/ppwstory3/post_base.html
{% extends "ppwstory3/base.html" %}

{% block content %}
<h1>{% block title %}{% endblock %}</h1>
<p>{% block date %}{% endblock %}</p>
<div class="post">
    {% block main %}
    {% endblock %}
</div>
{% endblock %}
{% block sidebar %}
<p>Learning web development. Enthutiastic in learning new stuffs.</p>
{% endblock %}

templates/ppwstory3/posts/1.html
{% extends "ppwstory3/post_base.html" %}

{% block title %}Story 4 is live!{% endblock %}

{% block date %}10 October 2020{% endblock %}

{% load static %}
{% block main %}
<img alt="Illustration of webdev" src="{% static 'ppwstory3/img/web-development.jpg' %}">
<div class="maintext">
    <p>
        I just finished PPW Story 4, here's my experience. Creating web using Django is super fun! You just need to deal with routing, views, and templates in order to make a simple blog. Besides, the template system is very pratical and it's easy to adjust.
    </p>
    <p>
        Finally, I'm getting used to creating html and understand all the tags. In my first experience with creating web is that I don't know all the tags. But, really, you shouldn't have know all the tags, should you? All you need is to see the documentation to find something you could use. Don't be afraid to try and fail. 
    </p>
    <p>   
        The web layout is created by CSS and bootstrap, interesting, isn't it? You just have to set the CSS rules and let the users' browsers to load it for you. Surprisingly, there is such thing as CSS frameworks to be included in html such as Bootstraps, Foundation, Pure, Bulma, etc.
    </p> 
    <p>
        This post is typed directly on html to be sent when you want to see it. Probably there is more effective way to use it, but I think this should be enough for the moment. Next time, I might use database to load the post, cool right?
    </p>
    <p> 
        Creating your own web by Django is fun you should try it. Don't be hestitate and feel how it's easy to use once you have learn it, obviously.
    </p>
</div>
{% endblock %}

templates/ppwstory3/posts/2.html
{% extends "ppwstory3/post_base.html" %}

{% block title %}Story 5 is live!{% endblock %}

{% block date %}16 October 2020{% endblock %}

{% load static %}
{% block main %}
<img alt="Illustration of webdev" src="{% static 'ppwstory3/img/web-development.jpg' %}">
<div class="maintext">
    <p>
        Check out the new feature, MatkulList! This is an example of Django Models usage. You could add Matkuls and remove it. Right now, it's open for everyone!
    </p>
    <p>
        Also, I learned about Django Forms. So I could just use form directly instead of traditional html form way. I even found an interesting template using django-bootstrap4, so I only need to use it and viola! The form is done and it looks pleasing.
    </p>
    <p>   
        I also learn about validations. I override the clean method so if it's not an valid input, the web will send it back with message. It looks cool, right?
    </p> 
    <p>
        I'd like to use Django models to replace this hardtyped article thingy, perhaps. Have fun trying out the feature!
    </p>
</div>
{% endblock %}

templates/ppwstory3/profile.html
{% extends "ppwstory3/base.html" %}

{% block title %}William's Profile{% endblock %}
{% load static %}
{% block content %}
<h1>My Profile</h1>
<h2>Description</h2>
<p>I love to learn new things, but sometimes I got bored and move on to other things. Learned programming earlier in high school, but I still have much to learn.</p>
<h2>Experience</h2>
<ul style="list-style-type: circle; margin-left: 50px;">
    <li>
        <b>Teaching Assistant of Introduction to Digital Systems</b>
        <p>September 2020 - Present<br>
        I help creating tasks and assist students in Introduction to Digital Systems.</p>
    </li>
    <li>
        <b>Junior Member of Network Security and Operating System (NetSOS) SIG in RISTEK, Faculty of Computer Science, Universitas Indonesia</b>
        <p>March 2019 - Present<br>
        In this group, I learned web and app security and test my skills in Capture The Flag competitions.</p>
    </li>
    <li>
        <b>Staff of Capture The Flag Competition</b>
        <p>March 2019 - Present<br>
        I'm assigned to a group whose job was to design challenges for HackerClass, Elimination round, and Final round in jeopardy format.</p>
    </li>
</ul>
<h2>Achievements</h2>
<ul style="list-style-type: circle; margin-left: 50px;">
    <li>
        <b>2nd Place in CTF Pekan RISTEK 2019</b>
        <p>This is an introductory Capture The Flag by RISTEK where we solve basic and easy challenges</p>
    </li>
</ul>
<h2>Skills</h2>
<ul style="list-style-type: circle; margin-left: 50px;">
    <li>
        <b>Basic Programming (Java, Python, C++)</b>
        <p>I have learned Java and Python since I'm entering University. Now, I'm learning to create and use effective algorithms.</p>
    </li>
    <li>
        <b>Basic Web Programming (Django)</b>
        <p>I could create basic web application. I usually create the application using Django.</p>
    </li>
</ul>

{% endblock %}
{% block sidebar %}
<h2>Contact</h2>
<p>Email: william92@ui.ac.id</p>
<h2>Social Media</h2>
<div style="display: inline-block; margin-bottom: 20px;">
    <a href="https://twitter.com/hori_75" ><img src="{% static 'ppwstory3/img/twitter.png' %}" alt="twitter" style="width: 50px; height: 50px;"></a>
    <a href="https://www.linkedin.com/in/william-8611851a0/"><img src="{% static 'ppwstory1/linkedin.png' %}" alt="Linkedin" style="max-width: 59px; max-height: 59px;"></a>
</div>
{% endblock %}